version: "3"

services:
  strapi-blog:
    build: https://github.com/riuGlobal/strapi-blog.git
    container_name: ${STRAPI_BLOG_CONTAINER_NAME:-strapi-blog}
    volumes:
      - ${PWD}/strapi-data:/strapi-data

  strapi-blog-web:
    depends_on:
      - strapi-blog
    build: https://github.com/riuGlobal/strapi-blog-web.git
    container_name: ${STRAPI_BLOG_WEB_CONTAINER_NAME:-strapi-blog-web}
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL

