version: "3"

services:
  strapi:
    image: strapi/strapi:3.6.5-alpine
    container_name: strapi
    environment:
      - DATABASE_CLIENT
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    volumes:
      - ${PWD}/strapi-data:/srv/app
