version: "3"

services:
  strapi-blog:
    build: https://github.com/riuGlobal/strapi-blog.git
    volumes:
      - ${PWD}/strapi-data:/strapi-data

  strapi-blog-web:
    depends_on:
      - strapi-blog
    build: https://github.com/riuGlobal/strapi-blog-web.git
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL

